AllCops:
  Include:
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/Appraisals'
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/bundle/**/*'

# Offense count: 1
Lint/Debugger:
  Enabled: false

# Offense count: 1
Lint/UselessAccessModifier:
  Enabled: false

# Offense count: 1
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 81

# Offense count: 5
Style/Documentation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/IndentationWidth:
  Enabled: false

# Offense count: 1
Metrics/AbcSize:
  Max: 20

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: false
