language: ruby
rvm:
  - 1.9.3
  - 2.1.2
gemfile:
  - gemfiles/activesupport_3.gemfile
  - gemfiles/activesupport_4.gemfile
script:
  - bundle exec cane --no-doc
  - bundle exec rubocop
  - bundle exec rspec
notifications:
  email: false
